fragment NodoFields on Nodo {
    id
    activo
    eleccionId
    createdAt
    updatedAt
}

query GetNodosByEleccion($eleccionId: ID!) {
    nodosByEleccion(eleccionId: $eleccionId) {
        ...NodoFields
    }
}

query GetNodo($id: ID!) {
    nodo(id: $id) {
        ...NodoFields
    }
}

mutation CrearNodo($eleccionId: ID!) {
    crearNodo(eleccionId: $eleccionId) {
        ...NodoFields
    }
}

mutation GenerarSecretoNodo($nodoId: ID!) {
    generarSecretoNodo(nodoId: $nodoId) {
        nodoId
        secreto
    }
}
